baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 10

[params]
  contentTypeName = "posts"
  themeColor = "red"
  showMenuItems = 3
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  # favicon = "favicon.ico"
  showLastUpdated = false

[params.twitter]
  creator = "avarx"
  site = "https://www.avarx.io"

[languages]
  [languages.en]
    languageName = "English"
    title = "www.avarx.io"
    subtitle = "Personal notes"
    owner = "avarx"
    keywords = "avarx, security, gaming"
    copyright = "avarx"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "avarx"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "cve"
        name = "CVE"
        url = "/cve"
